import { useState } from "react";
import {
  Download,
  FileText,
  Search,
  Shield,
  ShieldAlert,
} from "lucide-react";
import { openForensicReport } from "../services/api";
import RiskBadge from "../components/RiskBadge";

function Reports({ analysis, onNavigate }) {
  const [search, setSearch] = useState("");

  const reportAvailable = analysis?.forensic_report?.available === true;
  const filename        = analysis?.forensic_report?.filename || "";
  const caseId          = analysis?.case_id || "";

  const matchesSearch =
    !search ||
    filename.toLowerCase().includes(search.toLowerCase()) ||
    caseId.toLowerCase().includes(search.toLowerCase());

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <p className="page-eyebrow">FORENSIC DOCUMENTATION</p>
          <h2 className="page-title">Forensic Reports</h2>
          <p className="page-desc">
            Download evidence-backed PDF reports from MailTrace AI investigations.
          </p>
        </div>
      </div>

      {/* Search toolbar */}
      <div className="toolbar">
        <div className="toolbar-search">
          <Search size={14} />
          <input
            type="text"
            placeholder="Search report name or case ID…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
      </div>

      {/* No analysis yet */}
      {!analysis ? (
        <div className="card card--empty">
          <FileText size={36} />
          <h3>No reports available</h3>
          <p>
            Run an email investigation first. MailTrace AI generates a
            forensic PDF report automatically after each analysis.
          </p>
          <button type="button" className="btn-primary" onClick={() => onNavigate("analyze")}>
            Analyze Email
          </button>
        </div>
      ) : !matchesSearch ? (
        <div className="card card--empty">
          <Search size={28} />
          <h3>No matching report</h3>
          <p>Try a different search term.</p>
        </div>
      ) : (
        <div className="card">
          <div className="card-header">
            <div>
              <h3 className="card-title">Available Reports</h3>
              <p className="card-desc">1 report generated</p>
            </div>
            <FileText size={16} className="card-header-icon" />
          </div>

          <div className="report-row">
            <div className="report-row-icon">
              <FileText size={22} />
            </div>
            <div className="report-row-body">
              <strong className="report-filename">
                {filename || `${caseId}_forensic_report.pdf`}
              </strong>
              <span className="report-case-id">Case: {caseId || "—"}</span>
              <span className="report-meta">
                Subject: {analysis.email?.subject || "—"} ·{" "}
                Sender: {analysis.email?.sender || "—"}
              </span>
            </div>
            <div className="report-row-right">
              <RiskBadge level={analysis.risk?.level} />
              <div className={`report-status-badge ${reportAvailable ? "report-status--ready" : "report-status--unavailable"}`}>
                {reportAvailable ? (
                  <><Shield size={12} /> Ready</>
                ) : (
                  <><ShieldAlert size={12} /> Unavailable</>
                )}
              </div>
              <button
                type="button"
                className="btn-primary"
                disabled={!reportAvailable}
                onClick={() => openForensicReport(caseId)}
              >
                <Download size={14} />
                Download PDF
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Info panel */}
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Report Information</h3>
        </div>
        <div className="field-list">
          <FieldRow label="Format"         value="PDF — generated by MailTrace AI backend" />
          <FieldRow label="Endpoint"       value="GET /reports/{case_id}" mono />
          <FieldRow label="Contents"
            value="Email metadata, threat classification, risk score, forensic signals, IOCs, geo intelligence, evidence breakdown"
          />
          <FieldRow label="Current Case"   value={caseId || "No active investigation"} mono={!!caseId} />
          <FieldRow label="Storage"        value="Backend /reports/ directory (backend filesystem)" />
        </div>
      </div>
    </div>
  );
}

function FieldRow({ label, value, mono = false }) {
  return (
    <div className="field-row">
      <span className="field-label">{label}</span>
      <span className={`field-value${mono ? " monospace" : ""}`}>{value || "—"}</span>
    </div>
  );
}

export default Reports;
